const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('userscripts/strudel-samples.user.js', 'utf8');
const helpers = source.split('// BEGIN MAP DISCOVERY (standalone helpers tested with Node)')[1].split('// END MAP DISCOVERY')[0];
const sandbox = {URL};
vm.createContext(sandbox);
vm.runInContext(helpers + ';this.parse = sampleMaps;', sandbox);
const parse = code => Array.from(sandbox.parse(code));
const root = 'https://raw.githubusercontent.com/a/b/';
assert.deepEqual(parse("samples('github:a/b/hyperpop')"), [root+'hyperpop/strudel.json']);
assert.deepEqual(parse("samples('github:a/b')"), [root+'main/strudel.json']);
assert.deepEqual(parse("samples('github:a/b/x'); samples('github:a/b/y')"), [root+'x/strudel.json',root+'y/strudel.json']);
assert.deepEqual(parse("samples('https://example.com/pack.json?v=2')"), ['https://example.com/pack.json?v=2']);
assert.deepEqual(parse('// samples("github:a/b/no")\nsamples /* ok */ ("github:a/b/yes")'), [root+'yes/strudel.json']);
assert.deepEqual(parse('/* samples("github:a/b/no") */\nconst text = \'samples("github:a/b/no")\';'), []);
assert.deepEqual(parse('samples(variable); samples(`github:a/b/${branch}`); samples("github:a/b/" + branch)'), []);
assert.deepEqual(parse('samples("github:a/b/x");samples("github:a/b/x")'), [root+'x/strudel.json']);
assert.deepEqual(parse(''), []);
assert.deepEqual(parse('samples("github:a/b/x'), []);
console.log('Map discovery: 10 checks passed');
